package com.example.soundscapemapper.ui.theme

import androidx.compose.ui.graphics.Color

// ===== Paleta "Cuidado acústico": teal de control, menta segura, arena y coral =====
// El objetivo es transmitir calma y que el usuario sienta que tiene el control:
// nada de rojos de alarma militar; los avisos se dan en tonos tibios y suaves.
val SaludPrimary = Color(0xFF00695C)
val SaludOnPrimary = Color(0xFFFFFFFF)
val SaludPrimaryContainer = Color(0xFFB2DFDB)
val SaludOnPrimaryContainer = Color(0xFF00201B)
val SaludSecondary = Color(0xFF4DB6AC)
val SaludOnSecondary = Color(0xFFFFFFFF)
val SaludSecondaryContainer = Color(0xFFD5E8DA)
val SaludOnSecondaryContainer = Color(0xFF0E2017)
val SaludTertiary = Color(0xFF5B8DB8)
val SaludOnTertiary = Color(0xFFFFFFFF)
val SaludTertiaryContainer = Color(0xFFD6E4F1)
val SaludOnTertiaryContainer = Color(0xFF10293F)
val SaludError = Color(0xFFBA1A1A)
val SaludOnError = Color(0xFFFFFFFF)
val SaludErrorContainer = Color(0xFFFFDAD6)
val SaludOnErrorContainer = Color(0xFF410002)
val SaludBackground = Color(0xFFF7F9F6)
val SaludOnBackground = Color(0xFF1A1C19)
val SaludSurface = Color(0xFFFFFFFF)
val SaludOnSurface = Color(0xFF1A1C19)
val SaludSurfaceVariant = Color(0xFFE0EAE4)
val SaludOnSurfaceVariant = Color(0xFF454D47)
val SaludOutline = Color(0xFF7A8380)

// ===== Paleta oscura =====
val SaludPrimaryDark = Color(0xFF80CBC4)
val SaludOnPrimaryDark = Color(0xFF00332D)
val SaludPrimaryContainerDark = Color(0xFF0E5048)
val SaludOnPrimaryContainerDark = Color(0xFFA7E6DE)
val SaludSecondaryDark = Color(0xFFB5CCC1)
val SaludOnSecondaryDark = Color(0xFF21342B)
val SaludSecondaryContainerDark = Color(0xFF384B41)
val SaludOnSecondaryContainerDark = Color(0xFFD1E8DB)
val SaludTertiaryDark = Color(0xFFA6C8E8)
val SaludOnTertiaryDark = Color(0xFF1E3A52)
val SaludTertiaryContainerDark = Color(0xFF3A5270)
val SaludOnTertiaryContainerDark = Color(0xFFD6E4F1)
val SaludErrorDark = Color(0xFFFFB4AB)
val SaludOnErrorDark = Color(0xFF690005)
val SaludErrorContainerDark = Color(0xFF93000A)
val SaludOnErrorContainerDark = Color(0xFFFFDAD6)
val SaludBackgroundDark = Color(0xFF101412)
val SaludOnBackgroundDark = Color(0xFFDFE4DB)
val SaludSurfaceDark = Color(0xFF101412)
val SaludOnSurfaceDark = Color(0xFFDFE4DB)
val SaludSurfaceVariantDark = Color(0xFF3F4943)
val SaludOnSurfaceVariantDark = Color(0xFFBFC9C2)
val SaludOutlineDark = Color(0xFF8A938C)
