package com.example.soundscapemapper.ui.theme

import androidx.compose.ui.graphics.Color

// ===== Paleta "Salud": verde seguro, ámbar precaución, rojo peligro =====
val SaludPrimary = Color(0xFF2E7D32)
val SaludOnPrimary = Color(0xFFFFFFFF)
val SaludPrimaryContainer = Color(0xFFB7F0B5)
val SaludOnPrimaryContainer = Color(0xFF003909)
val SaludSecondary = Color(0xFF52634F)
val SaludOnSecondary = Color(0xFFFFFFFF)
val SaludSecondaryContainer = Color(0xFFD5E8D0)
val SaludOnSecondaryContainer = Color(0xFF101F10)
val SaludTertiary = Color(0xFF38656A)
val SaludOnTertiary = Color(0xFFFFFFFF)
val SaludTertiaryContainer = Color(0xFFBBEBF0)
val SaludOnTertiaryContainer = Color(0xFF002024)
val SaludError = Color(0xFFBA1A1A)
val SaludOnError = Color(0xFFFFFFFF)
val SaludErrorContainer = Color(0xFFFFDAD6)
val SaludOnErrorContainer = Color(0xFF410002)
val SaludBackground = Color(0xFFF7FBF4)
val SaludOnBackground = Color(0xFF1A1C19)
val SaludSurface = Color(0xFFF7FBF4)
val SaludOnSurface = Color(0xFF1A1C19)
val SaludSurfaceVariant = Color(0xFFDCE5D8)
val SaludOnSurfaceVariant = Color(0xFF404943)
val SaludOutline = Color(0xFF70796F)

// ===== Paleta oscura =====
val SaludPrimaryDark = Color(0xFF85DB8A)
val SaludOnPrimaryDark = Color(0xFF003909)
val SaludPrimaryContainerDark = Color(0xFF15591D)
val SaludOnPrimaryContainerDark = Color(0xFFA1F2A4)
val SaludSecondaryDark = Color(0xFFB9CCB4)
val SaludOnSecondaryDark = Color(0xFF243425)
val SaludSecondaryContainerDark = Color(0xFF3A4B3B)
val SaludOnSecondaryContainerDark = Color(0xFFD5E8D0)
val SaludTertiaryDark = Color(0xFF9FCFD4)
val SaludOnTertiaryDark = Color(0xFF00363B)
val SaludTertiaryContainerDark = Color(0xFF1E4D52)
val SaludOnTertiaryContainerDark = Color(0xFFBBEBF0)
val SaludErrorDark = Color(0xFFFFB4AB)
val SaludOnErrorDark = Color(0xFF690005)
val SaludErrorContainerDark = Color(0xFF93000A)
val SaludOnErrorContainerDark = Color(0xFFFFDAD6)
val SaludBackgroundDark = Color(0xFF0F1510)
val SaludOnBackgroundDark = Color(0xFFDFE4DB)
val SaludSurfaceDark = Color(0xFF0F1510)
val SaludOnSurfaceDark = Color(0xFFDFE4DB)
val SaludSurfaceVariantDark = Color(0xFF404943)
val SaludOnSurfaceVariantDark = Color(0xFFC0C9BC)
val SaludOutlineDark = Color(0xFF8A9388)
